### PR TITLE
Update dict.js

### PR DESCRIPTION
**Pull request by jojozp5261**

### CODE REVIEW

**Comment by TatriX** [comment]
Could you please make one PR with both commits?

**Comment by jojozp5261** [comment]
whats PR?

**Comment by TatriX** [comment]
Pull Request. I think you can push changes from #128 to this PR.

**Comment by jojozp5261** [comment]
I didnt understand it . I havent use this system before :(

**Comment by TatriX** [comment]
Ok, nevermind. I'll merge both commits.

**Comment by jojozp5261** [comment]
thx,keep working now :P

**Pull request merged**
