### PR TITLE
Update dict.js

### PR DESCRIPTION
**Pull request by niweiqi**

### CODE REVIEW

**Comment by TatriX** [comment]
Awesome, thank you!

**Comment by niweiqi** [comment]
This translation is traditional Chinese. Can you add another simplified Chinese text? I can do it well

**Comment by TatriX** [comment]
Sure, you can copy `zh-cht` directory to `zh-chs` and edit it.

**Comment by niweiqi** [comment]
It was a mistake just now

**Comment by niweiqi** [comment]
I don't know how to add a zh-chs folder here. Can you help me?

**Comment by TatriX** [comment]
Do you use github's web interface to edit translations?

**Comment by niweiqi** [comment]
The simplified Chinese text is ready, but I don't know how to upload it

**Comment by niweiqi** [comment]
I need you to add a zh-chs folder to github's web

**Comment by TatriX** [comment]
See 762501b133e1644d32639f561af530ef9af8ef64

**Comment by niweiqi** [comment]
OK, I'll continue translating

**Comment by niweiqi** [comment]
How long will it take to add to the game when the translation is complete?

**Comment by TatriX** [comment]
Well there are several options.
1) You can clone the repo and test the translation from your side
2) You can send a PR, then after I merge it you can test it from my server
3) Wait until it will be updated to the steam client with the nearest patch

**Comment by niweiqi** [comment]
Okay，i know

**Pull request merged**
