### PR TITLE
Update talks.js

### PR DESCRIPTION
**Pull request by niweiqi**

### CODE REVIEW

**Comment by AGPDev** [comment]
Thanks for contribution but, Really? You need make one pull request for every change, please make all changes and make one pull for all changes.

**Comment by niweiqi** [comment]
one pull？I do not understand what needs to be done.

**Comment by TatriX** [comment]
Well basically you should `fork` the repo, than `git clone` it, edit all the files you want, `git push` and then make a Pull Request.

**Comment by TatriX** [comment]
Could you please help with a steam page translation?

**Comment by niweiqi** [comment]
I am not a programmer, so I am sorry if I have trouble you

**Comment by niweiqi** [comment]
Okay, I can.I would like to know what the meaning of the game name

**Comment by TatriX** [comment]
Could you join our discord channel: https://discord.gg/kvyp3R2

The name is a deformation of the Russian word meaning `bagel` and a slang name for a `Roguelike` which is totally unrelated.

konata_by_aolas123

**Comment by niweiqi** [comment]
I translated imaging 《native land》 like this, okay?

I've finished translating steam page translation. How can I get it for you?

**Comment by TatriX** [comment]
Please mail it to the info@rogalia.ru

**Pull request merged**
