### PR TITLE
Include Windows symlink fix and update README

### PR DESCRIPTION
**Pull request by fabianPas**

### CODE REVIEW

**Comment by TatriX** [comment]
Pull latest changes from upstream please.

**Comment by fabianPas** [comment]
I've done that.

**Comment by TatriX** [comment]
Well it's broken.

**Comment by fabianPas** [comment]
Oh really? That's so weird. Github noted there wouldn't be any merge conflicts. Where does it go wrong?

**Comment by TatriX** [comment]
It included file changes from your old commits, reverting my latest fixes. Check "Files changed" tab.

**Comment by fabianPas** [comment]
Ahh yeah, I see the entity.js changes indeed. My bad. Next time I'll use a new branch instead. Is it okay now? Or do you need me to perform any other steps?

**Comment by TatriX** [comment]
No it's ok now. Thanks!

**Pull request merged**
