### PR TITLE
Update items.js

### PR DESCRIPTION
**Pull request by niweiqi**

### CODE REVIEW

**Comment by TatriX** [comment]
What is "protable"?

**Comment by niweiqi** [comment]
I saw this in the Russian translation file, so I added this

**Comment by TatriX** [comment]
I think you misstyped it then. It should be `"portable": "...",`

**Comment by niweiqi** [comment]
I found the Japanese "dict" file than the Chinese more than a few hundred lines, I can add in the Chinese file?

**Comment by niweiqi** [comment]
Okay, I know

**Comment by TatriX** [comment]
Sure. Just use right syntax, i.e. `"word": "translation",`

**Pull request closed without merging**
