### PR TITLE
1st file translated to portuguese

### PR DESCRIPTION
**Pull request by spectre1999**
I'm still work on the other files. What's to be translated is only what's inside "lang" folder? Or is there anything else?

### CODE REVIEW

**Comment by TatriX** [comment]
Awesome thank you! Everything inside lang folder.

**Comment by TatriX** [comment]
I add your translation to a test server. If you want I can add a special branch on steam with it. Or you may simply fork the repo and use master branch.

**Comment by spectre1999** [comment]
If that's not too much trouble, you could add a branch on steam. It would be great if after everything's translated I could test it to see if everything is in the right context, but for now I'll fork the repository and put a pull request only after I've translated all of the files. I think that's better, don't you think?

**Comment by TatriX** [comment]
I can add partially finished translation without problem. If translation is missing it fallbacks to English.

**Comment by spectre1999** [comment]
That's awesome!

**Pull request merged**
